<?php

// Zeekr 001 PDI checklist content. Source: "PDI Checklist Zeekr 001".
// Grouped by Classification (the source's two-column pagination is cosmetic).
return [
    'formname'   => 'Zeekr 001 PDI',
    'title'      => 'Lista de verificación PDI — Zeekr 001',
    'info_title' => 'Hoja informativa sobre vehículos comerciales',
    'item_col'   => 'Elemento de verificación PDI',
    'cols'       => ['Resultado de la inspección', 'Nivel', 'Solucionar'],
    'level_desc' => 'Especificación de grado — S-300: seguro, reglamentario y de reparación inmediata. A-100: todos/la mayoría de los clientes responden con fuertes quejas y solicitan la reparación lo antes posible. B-50/30: requieren mantenimiento en la mayoría de los casos. C-10: normalmente no requiere mantenimiento.',
    'info' => [
        'i_socio'            => 'Socio de entrega',
        'i_almacenamiento'   => 'Tiempo de almacenamiento',
        'i_serie'            => 'Serie de coches',
        'i_version_com'      => 'Versión comercial',
        'i_chapa'            => 'Chapa',
        'i_recortar'         => 'Recortar',
        'i_suyo'             => 'Suyo',
        'i_centro'           => 'Centro',
        'i_modulo'           => 'Módulo',
        'i_maquina'          => 'Máquina eléctrica',
        'i_paq_opcional'     => 'Paquete opcional',
        'i_paq_software'     => 'Paquete de software',
        'i_inicio'           => 'Comienza el trabajo',
        'i_fin'              => 'Fin del trabajo',
    ],
    'footer' => ['final' => 'Resultado final', 'remark' => 'Observación', 'operator' => 'Operador'],
    'groups' => [
        [
            'class' => 'Versión del sistema y accesorios a bordo',
            'items' => [
                'Borre el código de avería y reinicie el ciclo de mantenimiento.',
                'OTA, escritura de LCDS, actualización del software del vehículo a la última versión.',
                'Verifique si la configuración del vehículo es consistente.',
                'Borrar la imagen de la cámara del salpicadero.',
                'Cancelación y liquidación de cuentas de vehículos.',
                'Indicador de kilometraje de conducción.',
                'Certificado de conformidad, código de frotamiento (VIN), foto, certificado de conformidad.',
                'Triángulo.',
                'Gancho de remolque.',
                'Bomba de aire.',
                'Sellador de neumáticos.',
                'Chaleco reflectante.',
                'Función de la llave, apariencia.',
            ],
        ],
        [
            'class' => 'Inspección del chasis y prueba en carretera',
            'items' => [
                'Tubo de freno.',
                'Línea de refrigerante.',
                'Conjunto de suspensión neumática.',
                'Brazo de suspensión / biela / subchasis / barra estabilizadora.',
                'Mecanismo / eje de dirección.',
                'Aspecto de la carcasa / soporte de la batería.',
                'Protector inferior.',
                'Sistema de dirección sin calado.',
                'El sistema de dirección es normal.',
                'Sistema de frenos sin vibración (judder).',
                'El sistema de frenos funciona correctamente.',
                'Sistema de frenos ligero (light brake system).',
                'Manual de usuario en papel.',
            ],
        ],
        [
            'class' => 'Apariencia',
            'items' => [
                'Ventanilla trasera izquierda / junta.',
                'Aspecto de las llantas y los neumáticos.',
                'Aspecto de ceja de rueda.',
                'Presión de los neumáticos.',
                'Guardabarros delantero derecho.',
                'Pilar A derecho.',
                'Espejo retrovisor derecho.',
                'Embellecedor triangular del espejo retrovisor derecho.',
                'Puerta trasera izquierda.',
                'Columna B izquierda.',
                'Puerta delantera izquierda.',
                'Panel de protección inferior de la puerta delantera izquierda.',
                'Manija de la puerta delantera izquierda.',
                'Ventana delantera izquierda / tira de sellado / corte de agua exterior.',
                'Pilar A izquierdo.',
                'Embellecedor triangular del espejo retrovisor izquierdo.',
                'Cámara de visión trasera derecha.',
                'Puerta delantera derecha.',
                'Columna B derecha.',
                'Panel de protección inferior de la puerta delantera derecha.',
                'Manija de la puerta delantera derecha.',
                'Ventana / junta delantera derecha.',
                'Franja brillante en el lado derecho de la carrocería, corte de agua exterior del cristal.',
                'Viga superior derecha.',
                'Puerta trasera derecha.',
                'Borde inferior derecho de la falda.',
                'Ventanilla / junta trasera derecha.',
                'Cristal de la ventana de la esquina trasera derecha.',
                'Panel de protección inferior de la puerta trasera derecha.',
                'Manija de la puerta trasera derecha.',
                'Pilar C derecho.',
                'Columna D derecha.',
                'Guardabarros trasero derecho.',
                'Alerón trasero / luz de freno alta.',
                'Cámara central del alerón trasero.',
                'Puerta de popa (portón trasero).',
                'Etiqueta del maletero.',
                'Parabrisas trasero.',
                'Limpiaparabrisas trasero.',
                'Luz trasera izquierda / derecha.',
                'Luces traseras.',
                'LOGO / logo trasero.',
                'Luz de matrícula.',
                'Cámara trasera.',
                'Parachoques trasero.',
                'Marco de la placa trasera.',
                'Radar trasero izquierda / centro / derecha.',
                'Luz lateral trasera izquierda / derecha.',
                'Columna D izquierda.',
                'Guardabarros trasero izquierdo.',
                'Espejo retrovisor del lado izquierdo.',
                'Cámara de visión trasera izquierda.',
                'Guardabarros delantero izquierdo.',
                'Puerto de carga delantero izquierdo.',
                'Indicador en la tapa del puerto de carga delantero izquierdo.',
                'Techo / antena.',
                'LiDAR del techo delantero.',
                'Cristal de tragaluz.',
                'Cubierta del motor delantero.',
                'Señal de consumo de energía en el parabrisas delantero / 3C.',
                'Luz de circulación diurna.',
                'Cámara frontal (China net).',
                'Lámpara de cabeza (faro).',
                'Parachoques delantero.',
                'Cámara frontal.',
                'Marco de la matrícula de seguridad delantera.',
                'Parachoques delantero debajo de la carrocería.',
                'Amortiguador de la cubierta frontal.',
                'Rayo / brillo superior izquierdo.',
                'Cubierta antipolvo de la góndola delantera.',
                'Almohadón.',
                'Cierre del capó.',
                'Tanque de canalización izquierda / derecha.',
                'Cubierta antipolvo / tira de sellado / algodón insonorizante para la tapa trasera del motor.',
                'Limpiaparabrisas delantero / boquilla del limpiaparabrisas izquierda / derecha.',
                'Puerto de llenado de agua de vidrio.',
                'Líquido de frenos.',
                'Refrigerante.',
                'Líquido de lavaparabrisas.',
                'Algodón insonorizante de la cubierta interior.',
                'Tira de sellado de la sala del motor.',
                'Identificador LOG de la cubierta.',
                'Kit.',
                'Enchufes de línea de alta y baja tensión.',
                'Caja de fusibles principal.',
                'Puerto de carga trasero izquierdo.',
                'Indicador en la tapa del puerto de carga.',
                'Cristal de esquina trasera izquierda.',
                'Panel de protección inferior de la puerta trasera izquierda.',
                'Dobladillo inferior izquierdo.',
                'Manija de la puerta trasera izquierda.',
                'Fotos del vehículo (4 fotos a 45°).',
            ],
        ],
        [
            'class' => 'Trim (interior)',
            'items' => [
                'Anillo de sellado / guía superior de la jamba de la puerta delantera izquierda.',
                'Panel interior de la puerta delantera izquierda.',
                'Tira de luz de la puerta delantera izquierda.',
                'Manija mecánica de la puerta delantera izquierda.',
                'Botón de apertura interior de la puerta delantera izquierda.',
                'Panel de control de la puerta delantera izquierda.',
                'Botón elevalunas de la puerta delantera izquierda.',
                'Ajuste del espejo retrovisor exterior.',
                'Caja de almacenamiento / alfombrilla antideslizante de la puerta delantera izquierda.',
                'Luz de la puerta delantera izquierda.',
                'Marco de la puerta delantera izquierda.',
                'Bisagra / limitador de la puerta delantera izquierda.',
                'Altavoz interior / exterior de la puerta delantera izquierda.',
                'Sello de la puerta delantera izquierda.',
                'Pedal / piso de la puerta delantera izquierda.',
                'Reposacabezas delantero izquierdo.',
                'Cuero del asiento delantero izquierdo.',
                'Cinturón de seguridad delantero izquierdo.',
                'Ajuste del asiento delantero izquierdo.',
                'Soporte lumbar del asiento delantero izquierdo.',
                'Calefacción / ventilación / masaje del asiento delantero izquierdo.',
                'Panel de tapizado interior del pilar A delantero izquierdo.',
                'Panel frontal del techo.',
                'Parasol lateral izquierdo.',
                'Ajuste del espejo retrovisor interior del coche.',
                'Salpicadero delantero izquierdo.',
                'Lámpara del cuadro con izquierda / derecha.',
                'Head-up display.',
                'Pantalla del instrumento de servicio.',
                'Salida delantera izquierda.',
                'Cuero delantero izquierdo.',
                'Ajuste del volante.',
                'Arnés y tubería.',
                'Señal de indicación de seguridad de la cabina.',
                'Ventilador de refrigeración.',
                'Función de carga externa.',
                'Función del sistema de aviso de estado de carga.',
                'Caja de almacenamiento de la cabina.',
                'Otros (relacionado con chasis / interior).',
                'Soporte lumbar del asiento delantero derecho.',
                'Masaje / calefacción / ventilación del asiento delantero derecho.',
                'Tira de luz de la puerta delantera derecha.',
                'Parasol lateral derecho.',
                'Área del techo delantero derecho.',
                'Panel de tapizado interior del pilar A delantero derecho.',
                'Salpicadero delantero derecho.',
                'Guantera derecha.',
                'Salida de aire acondicionado delantera derecha.',
                'Cuero del cuadro delantero derecho.',
                'Panel interior de la puerta trasera derecha.',
                'Manija mecánica de la puerta trasera derecha.',
                'Botón de apertura de la puerta trasera derecha.',
                'Botón elevalunas trasero derecho.',
                'Anillo de sellado / guía superior de la jamba de la puerta trasera derecha.',
                'Panel de control de la puerta trasera derecha.',
                'Caja de almacenamiento trasera derecha.',
                'Luz de la puerta trasera derecha.',
                'Marco de la puerta trasera derecha.',
                'Bisagra / limitador de la puerta trasera derecha.',
                'Pedal / piso de la puerta trasera derecha.',
                'Panel de tapizado interior del pilar B lateral derecho.',
                'Sello de la puerta trasera derecha.',
                'Reposacabezas del asiento trasero derecho.',
                'Ajuste del asiento trasero derecho.',
                'Cuero del asiento trasero derecho.',
                'Calefacción del asiento trasero derecho.',
                'Tapizado interior del área del techo trasero derecho.',
                'Caja del reposabrazos central del asiento trasero.',
                'Panel de control del aire acondicionado trasero.',
                'Interruptor del portón trasero.',
                'Varilla hidráulica del portón trasero.',
                'Megáfono.',
                'Calefacción del volante.',
                'Botón del volante.',
                'LOG del volante.',
                'Palanca de luz izquierda - detección de luz.',
                'Palanca de control del limpiaparabrisas derecho - detección del limpiaparabrisas.',
                'Refrigeración y calefacción del aire acondicionado.',
                'Ajuste del volumen y la dirección del aire acondicionado.',
                'Interruptor de la cubierta del motor.',
                'Pantalla central.',
                'Grabadora de tráfico (DVR).',
                'Reconocimiento de voz.',
                'Vista envolvente 360°.',
                'Área de botones de control central.',
                'Área del mecanismo de cambio.',
                'Portavasos.',
                'Puerto del encendedor delantero.',
                'Interfaz USB.',
                'Interfaz Tipo-C.',
                'Carga inalámbrica.',
                'Área del canal central.',
                'Área del apoyabrazos central.',
                'Anillo de sellado / guía superior de la jamba de la puerta delantera derecha.',
                'Panel interior de la puerta delantera derecha.',
                'Manija mecánica interior de la puerta delantera derecha.',
                'Botón de apertura de la puerta delantera derecha.',
                'Panel de control de la puerta delantera derecha.',
                'Botón elevalunas de la puerta delantera derecha.',
                'Caja de almacenamiento de la puerta delantera derecha.',
                'Luz de la puerta delantera derecha.',
                'Marco de la puerta delantera derecha.',
                'Sello de la puerta delantera derecha.',
                'Pedal / piso de la puerta delantera derecha.',
                'Reposacabezas del asiento delantero derecho.',
                'Cuero del asiento delantero derecho.',
                'Cinturón de seguridad delantero derecho.',
                'Ajuste del asiento delantero derecho.',
                'Luz interior del portón trasero.',
                'Interior del parabrisas trasero.',
                'Función de patada / almohadilla de goma amortiguada para el portón trasero.',
                'Panel interior del pilar C izquierdo / derecho.',
                'Cinta de sellado del maletero.',
                'Panel de tapizado superior del maletero.',
                'Paneles laterales / persianas del maletero.',
                'Encendedor trasero.',
                'Cubierta del compartimento de almacenamiento.',
                'Cubierta de la caja de herramientas.',
                'Tapizado del maletero.',
                'Respaldo del asiento de la segunda fila.',
                'Hebilla de montaje del asiento infantil.',
                'Anillo de sellado / guía de la jamba de la puerta trasera izquierda.',
                'Panel interior de la puerta trasera izquierda.',
                'Manija de brazo interior de la puerta trasera izquierda.',
                'Panel de control de la puerta trasera izquierda.',
                'Botón de apertura de la puerta trasera izquierda.',
                'Botón elevalunas de la puerta trasera izquierda.',
                'Tira de luz de la puerta trasera izquierda.',
                'Luz de la puerta trasera izquierda.',
                'Caja de almacenamiento de la puerta trasera izquierda.',
                'Marco de la puerta trasera izquierda.',
                'Bisagra / limitador de la puerta trasera izquierda.',
                'Pedal / piso de la puerta trasera izquierda.',
                'Panel interior del pilar B izquierdo.',
                'Reposacabezas del asiento trasero / central izquierdo.',
                'Cuero del asiento trasero / central izquierdo.',
                'Ajuste del asiento trasero / central izquierdo.',
                'Tapizado interior del área del techo trasero izquierdo.',
                'Cinturón de seguridad del asiento trasero / central izquierdo.',
                'Calefacción del asiento trasero / central izquierdo.',
                'Cubierta de la góndola delantera.',
                'Caja de fusibles delantera.',
                'Voltaje de la celda de bajo voltaje.',
                'Etiqueta de identificación (nameplate).',
                'Código del motor delantero y trasero.',
            ],
        ],
    ],
];
