<?php

// Zeekr 7X PDI checklist content. Source: "PDI Checklist 7X".
// Items are grouped by their Classification (the source's two-column pagination
// is cosmetic; the real structure is Classification -> items).
return [
    'formname'   => 'Zeekr 7X PDI',
    'title'      => 'PDI checklist — Zeekr 7X',
    'info_title' => 'Commercial Vehicle Information Sheet',
    'item_col'   => 'PDI check items',
    'cols'       => ['Check results', 'Level', 'Categorization'],
    'level_desc' => null,
    'info' => [
        'i_delivery_partner' => 'Delivery Partner',
        'i_inventory_time'   => 'Inventory time',
        'i_version'          => 'Version',
        'i_exterior'         => 'Exterior',
        'i_interior'         => 'Interior',
        'i_tire'             => 'Tire',
        'i_wheel_hub'        => 'Wheel hub',
        'i_component'        => 'Component',
        'i_motor'            => 'Motor',
        'i_optional_package' => 'Optional package',
        'i_software_package' => 'Software package',
        'i_operation_start'  => 'Operation start',
        'i_operation_end'    => 'Operation end',
    ],
    // Header info fields we can pre-fill from the searched vehicle (info-key => data token).
    'autofill' => [
        'i_delivery_partner' => 'company',
        'i_version'          => 'version',
        'i_exterior'         => 'colorexterior',
        'i_interior'         => 'colorinterior',
        'i_motor'            => 'motor',
    ],
    'footer' => ['final' => 'Final result', 'remark' => 'Remarks', 'operator' => 'Operator'],
    'remark_hint' => 'Runs, dirty spots, scratches, surface scoring, color deviation, paint bubbles, cracks, staining, peeling, damage, tactile protrusions, sharp edges, surface waviness, rust, fluid leakage, abrasion marks, mechanical interference, abnormal noise, looseness, deformation, oxidation, sticking, dead pixels, gap mismatch, software malfunction, black screen, start failure, card key malfunction.',
    'groups' => [
        [
            'class' => 'System version and vehicle accessories',
            'items' => [
                'ZDS flashing, OTA software upgrading to the latest version',
                'Vehicle configuration consistency',
                'Digital video recorder, album videos and photos clearing',
                'Head unit account logout and clearing',
                'DTCs clearing via ZDS',
                'Kilometer overruns clearing',
                'Software issue',
            ],
        ],
        [
            'class' => 'Vehicle accessories',
            'items' => [
                'Certificate of conformity, VIN imprint, photos, certificate of compliance',
                'Warning triangle',
                'Tow hook',
                'Air pump',
                'Tire sealant',
                'Reflective vest',
                'FOB key function and appearance',
                'Mechanical key',
                'User manual',
                'Floor mat',
                'USB flash disk',
            ],
        ],
        [
            'class' => 'Chassis check and road test',
            'items' => [
                'Brake pipe',
                'Suspension arm, link, subframe',
                'Battery housing',
                'Steering gear, axle shaft',
                'Undershield',
                'Steering system without sticking',
                'Normal steering system',
                'Brake system free of judder',
                'Normal brake system',
                'Light brake system',
            ],
        ],
        [
            'class' => 'Appearance',
            'items' => [
                'Vehicle photos (four, at 45°)',
                'Appearance of right front wheel hub and tire',
                'Front right tire date',
                'Front right tire pressure',
                'Front right wheel hub cover, nuts',
                'Front right wheel hub cover LOG',
                'Front right wheel caliper',
                'Front right wheel liner trim, clips',
                'Front right fender',
                'Front right wheel arch extension',
                'Front right HD camera',
                'Right rearview mirror',
                'Right A-pillar',
                'Right luggage rack - front, center, rear',
                'Front right quarter window glass',
                'Right rearview mirror camera',
                'Front right door panel',
                'Right B-pillar trim panel',
                'Front right door body side strip, door inner belt seal',
                'Front right door lower protection plate',
                'Front right door outer handle',
                'Right body side outer trim panel',
                'Rear right door panel',
                'Rear right door body side strip, door inner belt seal',
                'Rear right door lower trim panel',
                'Rear right door outer handle',
                'Right skirt trim panel assembly',
                'Rear right quarter window glass',
                'Rear right body side',
                'Right D-pillar trim strip',
                'Rear right wheel arch extension',
                'Appearance of rear right wheel hub and tire',
                'Rear right tire date',
                'Rear right tire pressure',
                'Rear right wheel hub cover, nuts',
                'Rear right wheel hub cover LOG',
                'Rear right wheel caliper',
                'Rear right wheel liner trim, clips',
                'Tailgate trim panel',
                'High mounted stop lamp',
                'Tailgate appearance',
                'Rear windshield',
                'Tailgate combination lamp',
                'Right rear lamp',
                'Left rear lamp',
                'Rear LOGO/label',
                'License plate lamp',
                'License plate frame (rear)',
                'Rear camera',
                'Rear bumper',
                'Rear bumper radar',
                'Rear bumper lower trim panel',
                'Rear right fog lamp',
                'Rear left fog lamp',
                'Left D-pillar trim strip',
                'Rear left quarter window glass',
                'Rear left body side',
                'Charging port cover outer panel',
                'Indication mark for inside of charging port cover',
                'Rear left wheel arch extension',
                'Rear left wheel liner trim, clips',
                'Appearance of rear left wheel hub and tire',
                'Rear left tire date',
                'Rear left tire pressure',
                'Rear left wheel hub cover, nuts',
                'Rear left wheel hub cover LOG',
                'Rear left caliper',
                'Rear left door outer panel',
                'Rear left door body side strip, door inner belt seal',
                'Rear left door outer handle',
                'Rear left door lower trim panel',
                'Left skirt trim panel assembly',
                'Left B-pillar trim panel',
                'Front left door outer panel',
                'Front left door lower trim panel',
                'Front left door outer handle',
                'Left A-pillar',
                'Left luggage rack - front, center, rear',
                'Front left quarter window glass',
                'Left rearview mirror',
                'Left rearview mirror camera',
                'Front left fender',
                'Front left wheel arch extension',
                'Front left HD camera',
                'Appearance of front left wheel hub and tire',
                'Front left tire date',
                'Front left tire pressure',
                'Front left wheel hub cover, nuts',
                'Front left wheel hub cover LOG',
                'Front left wheel caliper',
                'Front left wheel liner trim, clips',
                'Panoramic sunroof',
                'Sunroof sealing strip',
                'Roof - front, rear, left, right',
                'Front top laser camera',
                'Front top laser camera trim panel',
                'Front windshield',
                'Front windshield 3C logo',
                'Front windshield energy consumption label',
                'Left front windshield sealing strip',
                'Right front windshield sealing strip',
                'Left and right wipers',
                'Left and right wiper arms',
                'Left and right wiper nut covers',
                'Front windshield gutter',
                'Hood',
                'Hood LOGO',
                'Daytime running lamps - left, right',
                'Headlamp - left, right',
                'Front fog lamp - left, right',
                'Front bumper',
                'Front bumper lower trim panel',
                'Front bumper camera',
                'License plate frame (front)',
                'Front bumper radar - left, center, right',
                'Active air inlet grille',
                'Millimeter-wave radar',
            ],
        ],
        [
            'class' => 'Front compartment',
            'items' => [
                'Front compartment inner',
                'Hood lock',
                'Hood bumper block',
                'Hood insulation',
                'Logos on both sides of hood inner',
                'Front compartment sealing strip',
                'Washer fluid filler',
                'Brake fluid',
                'Coolant',
                'Washer fluid',
                'Wiring harnesses and pipelines',
                'Safety indication mark for inside of hood',
                'Radiator fan',
                'Front compartment inner trim panel',
                'Front compartment inner storage box',
                'Wiper hose',
                'Wiper nozzle',
            ],
        ],
        [
            'class' => 'Interior trim',
            'items' => [
                'Front left door inner trim panel',
                'Front left door sealing strip',
                'Front left door plug',
                'Front left door opening button',
                'Front left door inner mechanical switch',
                'Front left door window control switch, panel',
                'Front left door window',
                'Outside rearview mirror adjustment (left)',
                'Front left door storage box, anti-slip pad',
                'Front left door horn',
                'Front left door lock, striker',
                'Front left door sealing strip (inner)',
                'Front left door VIN',
                'Front left door ambient light',
                'Front left door lamp',
                'Front left door A/C air vent',
                'Front left door hinge, limiter, wiring harness',
                'Front left door side step',
                'Front left door frame',
                'Left B-pillar tire pressure mark',
                'Front left door frame sealing strip',
                'Front left seat headrest',
                'Front left seat',
                'Front left seat back',
                'Front left seat belt',
                'Front left seat belt buckle',
                'Front left seat adjustment button',
                'Front left seat lumbar support',
                'Front left seat heating, ventilation, massage',
                'Front left A-pillar inner trim panel',
                'Front left A-pillar inner upper loudspeaker',
                'Front left A-pillar inner lower loudspeaker',
                'Front left roof, canopy area',
                'Front left roof safety handle',
                'Left B-pillar upper and lower inner trim panels',
                'Front left seat belt buckle (lower)',
                'Front left sun visor, sun visor mirror',
                'Inside rearview mirror adjustment',
                'Front center reading lamp',
                'Reading lamp control panel',
                'SOS button',
                'Camera cover',
                'Left instrument cover',
                'Left instrument panel',
                'Head Up Display',
                'Front left air vent',
                'Left instrument panel ambient light',
                'Instrument display',
                'Steering wheel adjustment',
                'Steering wheel',
                'Steering wheel LOGO',
                'Horn',
                'Steering wheel heating',
                'Steering wheel buttons',
                'Steering wheel airbag',
                'Steering wheel adjustment buttons',
                'Steering wheel ESC\\MODE button',
                'Left lighting control lever - light check',
                'Right gear control lever',
                'Right gear control lever - gear check',
                'Wiper',
                'Steering wheel trim cover',
                'Left instrument panel lower trim panel',
                'OBD socket',
                'Brake pedal',
                'Accelerator pedal',
                'Front left carpet, clips',
                'Instrument panel center loudspeaker',
                'Instrument panel center air vent',
                'Instrument panel center',
                'Head unit display',
                'Central control buttons below the head unit display',
                'A/C cooling and heating',
                'A/C air volume and direction adjustment',
                'Motor cover switch',
                'CSD infotainment screen',
                'Voice recognition',
                '360 view system',
                'Head unit display functions',
                'Wireless charging area',
                'Cup holder, cover',
                'Console',
                'Center armrest trim',
                'Center armrest',
                'Console storage box',
                'USB port',
                'Type C port',
                'Console rear display, functions',
                'Rear A/C control panel',
                'Vehicle refrigerator',
                'Rear left door inner trim panel',
                'Rear left door sealing strip',
                'Rear left door plug',
                'Rear left door opening button',
                'Rear left door inner mechanical switch',
                'Rear left door window control switch, panel',
                'Rear left door window',
                'Rear left door shade curtain, cover',
                'Rear left door storage box, anti-slip mat',
                'Rear left door horn',
                'Rear left door lock, striker',
                'Rear left door sealing strip (inner)',
                'Rear left door ambient light',
                'Rear left door lamp',
                'Rear left door inner trim panel strip',
                'Rear left door frame',
                'Rear left door frame sealing strip',
                'Rear left door hinge, limiter, wiring harness',
                'Rear left door side step',
                'Rear left seat headrest',
                'Rear left seat',
                'Rear left seat back',
                'Rear left seat belt',
                'Rear left seat adjustment button',
                'Rear left seat heating',
                'Rear seat center armrest box',
                'Function buttons in rear seat center armrest box',
                'Rear seat center armrest cup holder',
                'Rear seat center armrest inner control panel',
                'Rear carpet, clips',
                'Rear left C-pillar trim cover',
                'Rear left roof, canopy area',
                'Rear left roof safety handle',
                'Rear left roof loudspeaker cover',
                'Child seat buckle trim cover (left)',
                'Tailgate switch',
                'Tailgate inner lamp',
                'Rear windshield inner',
                'Tailgate sealing strip',
                'Tailgate upper trim panel',
                'Tailgate inner (12V power supply)',
                'Storage compartment cover',
                'Tool box cover',
                'Trunk trim cover',
                'Tailgate left and right trim panels',
                'Tailgate trim panel sliding rail guide channel',
                'Tailgate inner reading lamp',
                'Tailgate inner loudspeaker',
                'Tailgate inner right seat adjuster switch',
                'Tailgate inner right air spring adjustment switch',
                'Tailgate inner VIN, motor number',
                'Rear seat back',
                'Right rear door inner trim panel',
                'Rear right door sealing strip',
                'Rear right door plug',
                'Rear right door opening button',
                'Rear right door inner mechanical switch',
                'Rear right door window control switch, panel',
                'Rear right door window',
                'Rear right door shade curtain, cover',
                'Rear right door storage box, anti-slip mat',
                'Rear right door horn',
                'Rear right door lock, striker',
                'Rear right door sealing strip (inner)',
                'Rear right door ambient light',
                'Rear right door lamp',
                'Rear right door inner trim panel strip',
                'Rear right door frame',
                'Rear right door frame sealing strip',
                'Rear right door hinge, limiter, wiring harness',
                'Rear right door side step',
                'Rear right seat headrest',
                'Rear right seat',
                'Rear right seat back',
                'Rear right seat belt',
                'Rear right seat adjustment button',
                'Rear right seat heating',
                'Rear right C-pillar trim cover',
                'Rear right roof, canopy area',
                'Rear right roof safety handle',
                'Rear right roof loudspeaker cover',
                'Right child seat buckle trim cover',
                'Front right seat back',
                'Front right seat back tray table',
                'Front right seat back entertainment display',
                'Front right seat back opening button',
                'Right B-pillar upper and lower inner trim panels',
                'Front right seat belt buckle',
                'Front right door inner trim panel',
                'Front right door sealing strip',
                'Front right door plug',
                'Front right door opening button',
                'Front right door inner mechanical switch',
                'Front right door window control switch, panel',
                'Front right door window',
                'Right outside rearview mirror adjustment',
                'Front right door storage box, anti-slip mat',
                'Front right door horn',
                'Front right door lock, striker',
                'Front right door sealing strip (inner)',
                'Front right door VIN',
                'Front right door ambient light',
                'Front right door lamp',
                'Front right door A/C air vent',
                'Front right door hinge, limiter, wiring harness',
                'Front right door side step',
                'Front right door frame',
                'Right B-pillar nameplate',
                'Front right door frame sealing strip',
                'Front right seat headrest',
                'Front right seat',
                'Front right seat back (cushion)',
                'Front right seat belt',
                'Front right seat belt buckle',
                'Front right seat adjustment button',
                'Front right seat lumbar support',
                'Front right seat heating, ventilation, massage',
                'Front right A-pillar trim panel',
                'Front right A-pillar inner upper loudspeaker',
                'Front right A-pillar inner lower loudspeaker',
                'Front right roof, canopy area',
                'Front right roof safety handle',
                'Front right seat belt buckle (lower)',
                'Front right sun visor, sun visor mirror',
                'Right instrument cover',
                'Right instrument panel',
                'Front right air vent',
                'Right instrument panel ambient light',
                'Right glovebox',
                'Instrument panel lower trim panel',
                'Front right carpet, clips',
                'Nameplate label',
                'Front and rear motor codes',
            ],
        ],
    ],
];
