<?php

// Zeekr X PDI checklist content. Source: "TIS - Lista de Verificacion PDI Zeekr X".
return [
    'formname' => 'Zeekr X PDI',
    'title'    => 'Lista de verificación PDI — Zeekr X',
    'result_options' => [
        'ok' => 'De acuerdo',
        'ng' => 'No está bien',
        'na' => 'No aplicable',
    ],
    'header' => [
        'centro'   => 'Centro PDI',
        'ubicacion'=> 'Ubicación',
        'fecha'    => 'Fecha de inspección',
        'km'       => 'KM / Kilometraje',
        'firma'    => 'Firma del técnico',
        'hora_in'  => 'Hora en',
        'hora_out' => 'Se acabó el tiempo',
    ],
    // Header fields we can pre-fill from the searched vehicle / session (field-key => data token).
    'autofill' => [
        'centro' => 'company',
        'fecha'  => 'today',
        'firma'  => 'inspector',
    ],
    'appearance_legend' => 'X: Arañazo   O: Irregular   U: Espacio libre irregular   B: Daño',
    'sections' => [
        [
            'title' => 'INSPECCIÓN DEL CHASIS',
            'items' => [
                'Asegúrese de que el modo del vehículo sea normal. Si no lo es, cámbielo a modo normal.',
                'Verifique que las configuraciones de los vehículos sean consistentes y cumplan con los requisitos locales.',
                'Asegúrese de que el software esté actualizado y verifique que el vehículo no tenga ningún código de diagnóstico de avería (DTC). Si lo tiene, siga el proceso normal de solución de problemas.',
                'Restablecer el indicador de intervalo de mantenimiento y desactivar el modo de transporte.',
                'Borre el historial de información del buzón de mensajes/centro de mensajes.',
                'Compruebe si hay datos históricos en la grabadora de vídeo digital (DVR); si es así, borre los datos históricos mediante el comprobador.',
                'Lea y tome una foto de la diferencia de presión máxima y mínima de la celda de la batería para asegurarse de que la diferencia sea inferior a 50 mV. Guarde la foto en la orden de trabajo.',
                'Verifique y realice una impresión digital de la batería de bajo voltaje y asegúrese de que el voltaje de la batería sea mayor o igual a 12,5 V y que las conexiones de los polos sean normales. Guarde la impresión digital en la orden de trabajo.',
                'Asegúrese de que la placa de identificación, el código VIN, el motor (apto para modelos de combustible) y el número de motor (para modelos de nueva energía) sean correctos.',
                'El par de apriete de los pernos de la rueda se ajusta al valor especificado. Compruebe la presión de los neumáticos (incluido el neumático de repuesto).',
                'Compruebe el nivel de refrigerante, el nivel de líquido de frenos y el nivel de aceite del motor (apto para modelos de gasolina).',
                'Compruebe que el sistema eléctrico, el sistema de refrigeración y el sistema de frenos no presenten fugas.',
                'Agregue líquido de lavado, limpie el compartimento del motor.',
                'Asegúrese de que las partes del chasis no presenten daños ni fugas de aceite.',
                'Compruebe que la batería no presente daños (aplicable a modelos de nueva energía).',
            ],
        ],
        [
            'title' => 'INSPECCIÓN INTERIOR / FUNCIONES',
            'items' => [
                'Compruebe que el número de llaves, el aspecto, la función del sistema de acceso sin llave y el cierre centralizado funcionan correctamente.',
                'Compruebe que el nivel de batería del mando a distancia sea superior al 95 %. Asegúrese de que el funcionamiento del mando a distancia sea normal (EMTJ240302V0).',
                'Comprueba si la tarjeta NFC funciona correctamente.',
                'Compruebe que el funcionamiento del limpiaparabrisas sea normal.',
                'Compruebe que la función de ajuste del volante sea normal.',
                'Compruebe que la bocina funcione correctamente.',
                'Compruebe que la iluminación interior funcione correctamente.',
                'Compruebe que la iluminación exterior funcione correctamente.',
                'Compruebe que el funcionamiento de las ventanillas eléctricas sea normal, que no estén atascadas ni hagan ruido.',
                'Compruebe que el techo solar funciona correctamente.',
                'Verifique el panel de control del aire acondicionado, el puerto de salida, el funcionamiento del aire acondicionado y que el drenaje del aire acondicionado esté correcto.',
                'Comprueba que el sistema estéreo y el micrófono funcionen correctamente.',
                'Programar las emisoras de radio preferidas de los clientes.',
                'Compruebe que la red HU funciona correctamente y que la pantalla central funciona correctamente.',
                'Consulte el manual de usuario del automóvil (si lo tiene) que se va a utilizar.',
                'Comprobación de USB, Tipo-C, 12V, WPC: compruebe si USB, Tipo-C, 12V y la alimentación WPC funcionan correctamente con el equipo adecuado, como un teléfono inteligente, etc.',
                'Compruebe la seguridad del cinturón de seguridad del coche: estírelo, comprímalo, ajústelo y desabróchelo, y asegúrese de que el dispositivo de recordatorio del cinturón de seguridad funcione correctamente.',
                'Compruebe que los manuales, las herramientas de a bordo y demás elementos estén intactos.',
                'Asegúrese de que el interior esté limpio y revise si hay daños.',
                'No mueva las fundas protectoras del asiento ni arranque las etiquetas con la información del usuario.',
            ],
        ],
        [
            'title' => 'PRUEBA DE CONDUCCIÓN',
            'items' => [
                'Compruebe que todas las funciones del asiento funcionen correctamente, incluyendo la calefacción, la ventilación y el masaje, si corresponde.',
                'Compruebe si el freno de mano funciona correctamente.',
                'Asegúrese de que el vehículo arranque correctamente, que el panel de instrumentos se ilumine correctamente y que no se enciendan las luces indicadoras de falla.',
                'Realice una prueba de conducción de un máximo de 4 km en diferentes superficies, si es posible, y compruebe el ruido, las vibraciones y la aspereza del vehículo, así como los sistemas ADAS y la dirección. El kilometraje total debe ser inferior a 20 km en el momento de la entrega al cliente.',
                'Comprueba si el coche se desvía hacia un lado mientras conduces.',
                'Asegúrese de que no haya vibraciones anormales durante la conducción.',
                'Compruebe que el chasis y el módulo de suspensión neumática (si está equipado) funcionen correctamente.',
                'Comprueba que los espejos retrovisores interiores y exteriores funcionan correctamente.',
                'Compruebe que el freno, el cambio de marchas y la dirección funcionen correctamente.',
            ],
        ],
        [
            'title' => 'INSPECCIÓN DE LA PINTURA SUPERFICIAL',
            'items' => [
                'Comprueba que el cristal del vehículo no esté dañado.',
                'Compruebe que la pintura de la chapa metálica del parachoques delantero y del capó del motor no esté dañada.',
                'Compruebe que la pintura de la chapa lateral del guardabarros izquierdo, la puerta y la carrocería no esté dañada.',
                'Compruebe que la pintura de la chapa lateral derecha del guardabarros, la puerta y la carrocería no esté dañada.',
                'Compruebe que la pintura de la chapa metálica del parachoques trasero, el portón trasero o la tapa del maletero no esté dañada.',
                'Compruebe que la pintura de la chapa del techo no esté dañada.',
                'Compruebe el tope de la puerta y el pasador de retención, asegúrese de que no haya óxido ni ruido al abrir y cerrar las puertas.',
                'Revisa la carrocería en busca de óxido, corrosión y abolladuras.',
                'Compruebe la apertura y el cierre normales de la tapa del depósito de combustible (modelos de combustible), la tapa de carga (modelos de energías renovables) y la cubierta del habitáculo.',
                'Compruebe la función de carga normal del vehículo.',
                'Limpiar el vehículo.',
            ],
        ],
    ],
];
